name: 'ionicons_named'
description: 'A mapping library that maps the Stringified ionic icon name to the actual ionicon `IconData`.'
homepage: 'https://github.com/peiffer-innovations/ionicons_named'
version: '1.3.2+3'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: 'flutter'
  ionicons: '^0.2.2'

dev_dependencies: 
  flutter_lints: '^3.0.1'
  flutter_test: 
    sdk: 'flutter'
  http: '^1.2.1'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'uuid'
  - 'vector_math'
  - 'webdriver'
